version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action/*"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
